# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('language', models.CharField(max_length=2)),
                ('currency', models.CharField(max_length=2)),
            ],
        ),
    ]
